//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrzeugeinkauf
    {
        public int EinkaufId { get; set; }
        public string ListenpreisB { get; set; }
        public string EKPreisB { get; set; }
        public string Erstzulassung { get; set; }
        public string KMDatum { get; set; }
        public string Kaufdatum { get; set; }
        public string KMStand { get; set; }
    }
}
