//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kraftstoff
    {
        public int Id { get; set; }
        public string Kraftstoff1 { get; set; }
    }
}
