//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Termine
    {
        public int EreignisID { get; set; }
        public string Titel { get; set; }
        public string Start { get; set; }
        public string Ende { get; set; }
        public string Farbe { get; set; }
    }
}
