//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_uebersicht
    {
        public int Id { get; set; }
        public string Kennzeichen { get; set; }
        public string Marke { get; set; }
        public string Modell { get; set; }
        public string Fahrzeughalter { get; set; }
        public string Niederlassung { get; set; }
        public string Kraftstoff { get; set; }
        public Nullable<bool> Neuwagen { get; set; }
        public string Status { get; set; }
        public Nullable<int> EinkaufId { get; set; }
        public string ListenpreisB { get; set; }
        public string EKPreisB { get; set; }
        public string Erstzulassung { get; set; }
        public string KMDatum { get; set; }
        public string Kaufdatum { get; set; }
        public string KMStand { get; set; }
    }
}
